schema:
  - https://jirabackend.vercel.app/api/graphql
documents:
  - "src/**/*.graphql"
generates:
  src/utils/__generated__/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withRefetchFn: true
